services:
  backend:
    build:
      context: ./app
      target: builder
    container_name: backend
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: "no"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - postgres-network

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks: 
  postgres-network:
    driver: bridge